# Variables globales

SOURCE_DATA_BASE_PATH = "../data/"
SOURCE_DATA_FILENAME = SOURCE_DATA_BASE_PATH + "parque_consolidado_2023_ORIGINAL.txt"
TURISMO_ECO_ZERO_FILENAME_RAW = SOURCE_DATA_BASE_PATH + "turismos_eco-zero_raw.csv"
TURISMO_ECO_ZERO_FILENAME_FINAL = SOURCE_DATA_BASE_PATH + "turismos_eco-zero_final.csv"

TURISMO_OTROS_FILENAME_RAW = SOURCE_DATA_BASE_PATH + "turismos_otros_raw.csv"
TURISMO_OTROS_FILENAME_FINAL = SOURCE_DATA_BASE_PATH + "turismos_otros_final.csv"

CSV_SEPARADOR_COLUMNAS = "|"

VALUE_SIN_DETERMINAR = "* ND *"
NUM_VALUE_SIN_DETERMINAR = -10

GROUP_BY_COUNT_COLUMN = "COUNT"